### ISSUE TITLE
Lungs cannot be detected correctly

### ISSUE THREAD

**Issue by xiaoyongzhu** [dirtmaxim/lungs-finder#2]
![00000013_006](https://user-images.githubusercontent.com/1185090/34238189-4d6f8868-e5b5-11e7-8881-bbd78ec1bcbe.png)
Hi,

Thanks for publishing this library, it is super helpful!

One issue I found is that when dealing with a specific data (see attached), it does not return the images correctly. Looks like there is some bug somewhere.

**Comment by dirtmaxim** [comment]
Hi,
Classifiers were trained on normal and pathological lungs equally and should be able to find pathological lungs as good as normal. I tested your image:

![screen shot 2018-01-09 at 04 40 02](https://user-images.githubusercontent.com/11778655/34701094-5675c5f2-f4f7-11e7-8730-e1cf413800fa.png)

Haar, LBP and HOG correctly found left lung. It is fine that right lung is not detected. It seems that problem that HOG detected dark area under clavicle instead of nothing. The correct behavior in such case like that: no classifiers detect right lung, some classifiers detect left lung, left lung detection reflects to the right lung side and then you will get cropped lungs correctly. In this case it still gives correct lung crop despite not correct HOG Right detection:

![screen shot 2018-01-09 at 04 52 11](https://user-images.githubusercontent.com/11778655/34701381-e97a5bfa-f4f8-11e7-894f-cf404e8a9f09.png)

**Comment by xiaoyongzhu** [comment]
Thanks @dirtmaxim . I definitely agree with the approach you said, and I think it would be best if you an put a note on that in the README so people can use the APIs correctly in their applications.

BTW - what machine learning algorithm is it based on?

**Comment by uv-programmer** [comment]
I gave it a flower as input. It still gives out a positive result
